<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.9.0-alpha
 * FormDin Version: 4.7.5
 * 
 * System appev2 created in: 2019-09-10 09:04:46
 */

namespace api_controllers;

use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;

class AcessoAPI
{

    public function __construct()
    {
    }


    //--------------------------------------------------------------------------------
    private static function getParam(string $paramName, array $bodyRequest)
    {
        if( \ArrayHelper::has($paramName,$bodyRequest)){
            $paramName = $bodyRequest[$paramName];
        }else{
            throw new \InvalidArgumentException('Parametro '.$paramName.' não informado');
        }
        return $paramName;
    }

    //--------------------------------------------------------------------------------
    public static function login(Request $request, Response $response, array $args)
    {
        $bodyRequest = json_decode($request->getBody(),true);

        $login_user = self::getParam('login_user',$bodyRequest);
        $pwd_user   = self::getParam('pwd_user',$bodyRequest);

        $controller = new \Acesso;
        $msg = $controller->login($login_user,$pwd_user);
        $response = $response->withJson($msg);
        return $response;
    }
}