<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.9.0
 * 
 * System xxx created in: 2020-03-04 21:02:53
 */
class Log_acessoVO
{
    private $idlog_acesso = null;
    private $iduser = null;
    private $dat_acesso = null;
    private $idmenu = null;
    private $ip = null;
    public function __construct( $idlog_acesso=null, $iduser=null, $dat_acesso=null, $idmenu=null, $ip=null ) {
        $this->setIdlog_acesso( $idlog_acesso );
        $this->setIduser( $iduser );
        $this->setDat_acesso( $dat_acesso );
        $this->setIdmenu( $idmenu );
        $this->setIp( $ip );
    }
    //--------------------------------------------------------------------------------
    public function setIdlog_acesso( $strNewValue = null )
    {
        $this->idlog_acesso = $strNewValue;
    }
    public function getIdlog_acesso()
    {
        return $this->idlog_acesso;
    }
    //--------------------------------------------------------------------------------
    public function setIduser( $strNewValue = null )
    {
        $this->iduser = $strNewValue;
    }
    public function getIduser()
    {
        return $this->iduser;
    }
    //--------------------------------------------------------------------------------
    public function setDat_acesso( $strNewValue = null )
    {
        $this->dat_acesso = $strNewValue;
    }
    public function getDat_acesso()
    {
        return is_null( $this->dat_acesso ) ? date( 'Y-m-d h:i:s' ) : $this->dat_acesso;
    }
    //--------------------------------------------------------------------------------
    public function setIdmenu( $strNewValue = null )
    {
        $this->idmenu = $strNewValue;
    }
    public function getIdmenu()
    {
        return $this->idmenu;
    }
    //--------------------------------------------------------------------------------
    public function setIp( $strNewValue = null )
    {
        $this->ip = $strNewValue;
    }
    public function getIp()
    {
        return $this->ip;
    }
    //--------------------------------------------------------------------------------
}
?>