<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.9.0-alpha
 * FormDin Version: 4.7.5
 * 
 * System appev2 created in: 2019-09-10 09:04:47
 */
class Regiao
{


    private $dao = null;
    private $client = null;

    public function __construct($tpdo = null)
    {
        $this->client = new GuzzleHttp\Client(['base_uri' => 'http://localhost/formDin/appexemplo_v2.0/api/']);
    }
    public function getDao()
    {
        return $this->dao;
    }
    public function setDao($dao)
    {
        $this->dao = $dao;
    }
    //--------------------------------------------------------------------------------
    public function selectById( $id )
    {
        $response = $this->client->request('GET', 'regiao/'.$id);
        $contents = $response->getBody()->getContents();
        $result = json_decode($contents);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectCount( $where=null )
    {
        $result = $this->dao->selectCount( $where );
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectAllPagination( $orderBy=null, $where=null, $page=null,  $rowsPerPage= null)
    {
        $headers = [            
            'Accept'        => 'application/json'
        ];
        $response =  $this->client->request('GET', 'regiao/', [
            'headers' => $headers
        ]);
        if($response->getStatusCode()==200){
            $result = $response->getBody();
        }else{
            $result = 'erro';
        }        
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function selectAll( $orderBy=null, $where=null )
    {
        $response = $this->client->request('GET', 'regiao');
        $contents = $response->getBody()->getContents();
        $result = json_decode($contents);
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function save( RegiaoVO $objVo )
    {
        $objJson = FormDinHelper::convertVo2Json($objVo);
        $result = null;
        $response = null;
        $headers = [            
            'Accept'        => 'application/json'
        ];
        if( $objVo->getCod_regiao() ) {
            $response =  $this->client->request('PUT', 'regiao/'.$objVo->getCod_regiao(), [
                 'headers' => $headers
                ,'json'    => $objJson
            ]);
        } else {
            $response =  $this->client->request('POST', 'regiao/', [
                'headers' => $headers
                ,'json'    => $objJson
            ]);            
        }
        if($response->getStatusCode()==200){
            $result = 1;
        }else{
            $result = 'erro';
        }
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function delete( $id )
    {
        $result = $this->dao->delete( $id );
        return $result;
    }
    //--------------------------------------------------------------------------------
    public function getVoById( $id )
    {
        $result = $this->dao->getVoById( $id );
        return $result;
    }

}
?>