<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.11.0
 * FormDin Version: 4.9.0
 * 
 * System xxx created in: 2020-03-04 21:02:53
 */
class Acesso_tokensVO
{
    private $idacesso_tokens = null;
    private $iduser = null;
    private $token = null;
    private $refresh_token = null;
    private $expired_at = null;
    private $active = null;
    public function __construct( $idacesso_tokens=null, $iduser=null, $token=null, $refresh_token=null, $expired_at=null, $active=null ) {
        $this->setIdacesso_tokens( $idacesso_tokens );
        $this->setIduser( $iduser );
        $this->setToken( $token );
        $this->setRefresh_token( $refresh_token );
        $this->setExpired_at( $expired_at );
        $this->setActive( $active );
    }
    //--------------------------------------------------------------------------------
    public function setIdacesso_tokens( $strNewValue = null )
    {
        $this->idacesso_tokens = $strNewValue;
    }
    public function getIdacesso_tokens()
    {
        return $this->idacesso_tokens;
    }
    //--------------------------------------------------------------------------------
    public function setIduser( $strNewValue = null )
    {
        $this->iduser = $strNewValue;
    }
    public function getIduser()
    {
        return $this->iduser;
    }
    //--------------------------------------------------------------------------------
    public function setToken( $strNewValue = null )
    {
        $this->token = $strNewValue;
    }
    public function getToken()
    {
        return $this->token;
    }
    //--------------------------------------------------------------------------------
    public function setRefresh_token( $strNewValue = null )
    {
        $this->refresh_token = $strNewValue;
    }
    public function getRefresh_token()
    {
        return $this->refresh_token;
    }
    //--------------------------------------------------------------------------------
    public function setExpired_at( $strNewValue = null )
    {
        $this->expired_at = $strNewValue;
    }
    public function getExpired_at()
    {
        return $this->expired_at;
    }
    //--------------------------------------------------------------------------------
    public function setActive( $strNewValue = null )
    {
        $this->active = $strNewValue;
    }
    public function getActive()
    {
        return $this->active;
    }
    //--------------------------------------------------------------------------------
}
?>